name: "[point-utilities] Jest unit tests"
on: [pull_request]
jobs:
  tests_e2e:
    name: "[point-utilities] Run Jest unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Initialize Yarn and install package dependencies
        run: yarn
      - name: Build NPM package
        run: yarn prerelease
      - name: Run tests
        run: cd packages/point-utilities && yarn test